#!/bin/bash
# sync_session_state.sh — Consolidate CLI memory into shared state files
# Triggered by Claude Code hooks (PostToolUse on memory writes) or manually.
# Runs async so it never blocks Claude.
#
# What it does:
#   1. Reads CLI memory files + SHARED_CONTEXT
#   2. Writes a consolidated SESSION_STATE.md to .agents/
#   3. This file is readable by ALL instances (CLI + Desktop)
#
# Usage:
#   bash ~/theVault/System/Scripts/sync_session_state.sh
#   # Or with a trigger source label:
#   bash ~/theVault/System/Scripts/sync_session_state.sh "hook:PostToolUse"

set -euo pipefail

VAULT_ROOT="${HOME}/theVault"
CLI_MEMORY_DIR="${HOME}/.claude/projects/-Users-ericmanchester-theVault/memory"
AGENTS_DIR="${VAULT_ROOT}/.agents"
STATE_FILE="${AGENTS_DIR}/SESSION_STATE.md"
LOCK_FILE="/tmp/sync_session_state.lock"
TRIGGER="${1:-manual}"

# Prevent concurrent runs
if [ -f "$LOCK_FILE" ]; then
    LOCK_AGE=$(( $(date +%s) - $(stat -f %m "$LOCK_FILE" 2>/dev/null || echo 0) ))
    if [ "$LOCK_AGE" -lt 10 ]; then
        exit 0  # Another sync is running, skip silently
    fi
    rm -f "$LOCK_FILE"  # Stale lock, clean up
fi
touch "$LOCK_FILE"
trap 'rm -f "$LOCK_FILE"' EXIT

# Ensure target dir exists
mkdir -p "$AGENTS_DIR"

# Build consolidated state
NOW=$(date "+%Y-%m-%d %H:%M:%S")

cat > "$STATE_FILE" << HEADER
# Session State — Auto-Synced

_Last sync: ${NOW} (trigger: ${TRIGGER})_
_This file is auto-generated by sync_session_state.sh. Do not edit manually._
_All Claude instances (CLI + Desktop) should read this at session start._

HEADER

# Section 1: Current priorities (extract from priority memory if it exists)
PRIORITY_FILE="${CLI_MEMORY_DIR}/project_priorities_2026_03.md"
if [ -f "$PRIORITY_FILE" ]; then
    # Extract just the priority sections (skip frontmatter)
    echo "## Current Priorities" >> "$STATE_FILE"
    echo "" >> "$STATE_FILE"
    sed -n '/^## Project Priority Map/,$ p' "$PRIORITY_FILE" >> "$STATE_FILE"
    echo "" >> "$STATE_FILE"
fi

# Section 2: Active work from SHARED_CONTEXT
SHARED_CONTEXT="${AGENTS_DIR}/SHARED_CONTEXT.md"
if [ -f "$SHARED_CONTEXT" ]; then
    echo "---" >> "$STATE_FILE"
    echo "" >> "$STATE_FILE"
    echo "## Active Work & Handoffs" >> "$STATE_FILE"
    echo "" >> "$STATE_FILE"
    # Include everything after the header line
    sed -n '/^## Active Work/,$ p' "$SHARED_CONTEXT" >> "$STATE_FILE"
    echo "" >> "$STATE_FILE"
fi

# Section 3: Key reference files
REF_FILE="${CLI_MEMORY_DIR}/ref_key_files.md"
if [ -f "$REF_FILE" ]; then
    echo "---" >> "$STATE_FILE"
    echo "" >> "$STATE_FILE"
    echo "## Key File Locations" >> "$STATE_FILE"
    echo "" >> "$STATE_FILE"
    # Skip frontmatter, include table
    sed -n '/^|/,$ p' "$REF_FILE" >> "$STATE_FILE"
    echo "" >> "$STATE_FILE"
fi

# Section 4: Feedback rules (so Desktop sessions know user preferences)
echo "---" >> "$STATE_FILE"
echo "" >> "$STATE_FILE"
echo "## User Preferences & Feedback" >> "$STATE_FILE"
echo "" >> "$STATE_FILE"

for f in "${CLI_MEMORY_DIR}"/feedback_*.md; do
    [ -f "$f" ] || continue
    NAME=$(grep '^name:' "$f" | sed 's/^name: //')
    # Extract content after frontmatter (everything after second ---)
    CONTENT=$(awk 'BEGIN{c=0} /^---$/{c++; next} c>=2{print}' "$f")
    if [ -n "$NAME" ]; then
        echo "### ${NAME}" >> "$STATE_FILE"
        echo "$CONTENT" >> "$STATE_FILE"
        echo "" >> "$STATE_FILE"
    fi
done

# Section 5: Memory index for reference
MEMORY_INDEX="${CLI_MEMORY_DIR}/MEMORY.md"
if [ -f "$MEMORY_INDEX" ]; then
    echo "---" >> "$STATE_FILE"
    echo "" >> "$STATE_FILE"
    echo "## CLI Memory Index" >> "$STATE_FILE"
    echo "_These files live at \`~/.claude/projects/-Users-ericmanchester-theVault/memory/\`_" >> "$STATE_FILE"
    echo "" >> "$STATE_FILE"
    cat "$MEMORY_INDEX" >> "$STATE_FILE"
fi
